<a href="https://colab.research.google.com/github/Jayku88/Linear-Algebra/blob/main/19MAT105_Week_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Determinants

##Square Matrix

A matrix with $n$ rows and $n$ columns is called a square matrix of order $n$

##Determinants
A single value that contains many information related to a square matrix. If $A$ is the matrix, then determinant is denoted by $det(A)$

**Properties**

1.   $det(I)=1$
2.   If you exchange two rows of a matrix, you reverse the sign of its determinant from positive to negative or from negative to positive
3.   If we multiply one row of a matrix by $t$, the determinant is multiplied by $t$
4.   If two rows of a matrix are equal, its determinant is zero.
5.   If matrix has a row that is all zeros, its determinant is zero.
6.   The determinant of a **triangular** matrix is the product of the diagonal entries
7.   $det(A) = 0$ exactly when $A$ is **singular**
8.   $det(AB) = det(A)det(B)$
9.   $det(A^T)=det(A)$






### Property 1

In [ ]:
from sympy import *
A = Matrix([[1,0,0], [0,1,0], [0,0,1]])
print("Determinant of A is",det(A))
A

Determinant of A is 1


Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])

### Property 2

In [ ]:
from sympy import *
A = Matrix([[0,1,0], [1,0,0], [0,0,1]])
print("Determinant of A is",det(A))
A

Determinant of A is -1


Matrix([
[0, 1, 0],
[1, 0, 0],
[0, 0, 1]])

### Property 3

In [ ]:
from sympy import *
A = Matrix([[3,0,0], [0,1,0], [0,0,1]])
print("Determinant of A is",det(A))
A

Determinant of A is 3


Matrix([
[3, 0, 0],
[0, 1, 0],
[0, 0, 1]])

### Property 4

In [ ]:
from sympy import *
A = Matrix([[1,0,0], [1,0,0], [0,0,1]])
print("Determinant of A is",det(A))
A

Determinant of A is 0


Matrix([
[1, 0, 0],
[1, 0, 0],
[0, 0, 1]])

### Property 5

In [ ]:
from sympy import *
A = Matrix([[1,0,0], [0,1,0], [0,0,0]])
print("Determinant of A is",det(A))
A

Determinant of A is 0


Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 0]])

### Property 6

In [ ]:
from sympy import *
A = Matrix([[2,0,0], [0,3,0], [0,0,3]]) #Diagonal Matrix
print("Determinant of A is",det(A))
A

Determinant of A is 18


Matrix([
[2, 0, 0],
[0, 3, 0],
[0, 0, 3]])

In [ ]:
from sympy import *
A = Matrix([[2,1,2], [0,3,9], [0,0,3]]) #Upper Triangular Matrix
print("Determinant of A is",det(A))
A

Determinant of A is 18


Matrix([
[2, 1, 2],
[0, 3, 9],
[0, 0, 3]])

In [ ]:
from sympy import *
A = Matrix([[2,0,0], [6,3,0], [7,9,3]]) #Lower Triangular Matrix
print("Determinant of A is",det(A))
A

Determinant of A is 18


Matrix([
[2, 0, 0],
[6, 3, 0],
[7, 9, 3]])

### Property 7

In [ ]:
from sympy import *
A = Matrix([[1,2,3], [2,4,6], [7,7,7]]) #Inverse does not exists if determinant is zero
print("Determinant of A is",det(A))
A

Determinant of A is 0


Matrix([
[1, 2, 3],
[2, 4, 6],
[7, 7, 7]])

### Property 8

In [ ]:
from sympy import *
A = Matrix([[2,1,2], [0,3,9], [0,0,3]]) 
print("Determinant of A is",det(A))
B = Matrix([[2,0,0], [6,3,0], [7,9,3]]) 
print("Determinant of B is",det(B))
C=A*B
print("Determinant of AB is",det(C))

Determinant of A is 18
Determinant of B is 18
Determinant of AB is 324


### Property 9

In [ ]:
from sympy import *
A = Matrix([[24,21,6], [81,90,27], [21,27,9]]) 
print("Determinant of A is",det(A))
C=A.transpose()
print("Determinant of transpose of A is",det(C))

Determinant of A is 324
Determinant of transpose of A is 324


###Finding Inverse

If $A$ is an invertible matrix, then
$$A^{-1}=\frac{adj(A)}{det(A)}$$
$A$ is said to be invertible or non-singular if $det(A)\neq0$

Find inverse of following matrix
$$\begin{bmatrix}3&2&-1\\1&6&3\\2&-4&0\end{bmatrix}$$

In [ ]:
from sympy import *
M = Matrix([[3,2,-1], [1,6,3], [2,-4,0]])
M.inv()

Matrix([
[3/16, 1/16,  3/16],
[3/32, 1/32, -5/32],
[-1/4,  1/4,   1/4]])

###Cramer's Rule

If $Ax=b$ is a system of $n$ linear equations in $n$ unknowns such that $det(A)\neq0$, then the system has a unique solution. This solution is, $$x_1=\frac{det(A_1)}{det(A)},x_2=\frac{det(A_2)}{det(A)}.....x_n=\frac{det(A_n)}{det(A)}$$ where $A_j$ is the matrix obtained by replacing the entries in the $j'th$ column of $A$ by the entries in the matrix $$b=\begin{bmatrix}
b_1\\
b_2\\
..\\
..\\
b_n
\end{bmatrix}$$

Solve the following linear system using **Cramer's rule**
$$x_1+2x_3=6$$
$$-3x_1+4x_2+6x_3=30$$
$$-x_1-2x_2+3x_3=8$$

In [ ]:
from sympy import *
A = Matrix([[1,0,2], [-3,4,6], [-1,-2,3]])
print("Determinant of A is",det(A))
A1 = Matrix([[6,0,2], [30,4,6], [8,-2,3]])
print("Determinant of A1 is",det(A1))
A2 = Matrix([[1,6,2], [-3,30,6], [-1,8,3]])
print("Determinant of A2 is",det(A2))
A3 = Matrix([[1,0,6], [-3,4,30], [-1,-2,8]])
print("Determinant of A3 is",det(A3))
print("x1 = ",det(A1)/det(A))
print("x2 = ",det(A2)/det(A))
print("x3 = ",det(A3)/det(A))


Determinant of A is 44
Determinant of A1 is -40
Determinant of A2 is 72
Determinant of A3 is 152
x1 =  -10/11
x2 =  18/11
x3 =  38/11


#Eigen Values and Eigen Vectors

https://www.youtube.com/watch?v=PFDu9oVAE-g

For interpretation refer

A matrix $A$ acts on vectors $x$ like a function does, with input $x$ and output $Ax$. Eigenvectors are vectors for which $Ax$ is parallel to $x$. In other words:
$$Ax = \lambda x$$
In this equation, $x$ is an eigenvector of $A$ and $\lambda$ is an eigenvalue of $A$. 

**Equivalent Statements**

If $A$ is an $n\times n$ matrix, then following statements are equivalent

1.   $A$ is **invertible**
2.   $Ax=0$ has only **trivial** solution
3.   The **reduced row echelon form** of $A$ is $I_n$
4.   $Ax=b$ is **consistent** for every $n \times 1$ matrix $b$
5.   $det(A) \neq 0$
6.   The column vectors are **linearly independent**
7.   The row vectors are **linearly independent**
8.   The column vectors of $A$ **span** $R^n$
9.   The row vectors of $A$ **span** $R^n$
10.  The column vectors of $A$ form a **basis** for $R^n$
11.  The row vectors of $A$ form a **basis** for $R^n$
12.  $A$ has **rank** $n$
13.  **Dimension of column space** is $n$
14.  **Dimension of null space** is $0$
15.  $\lambda =0$ is not an eigen value of $A$



Find Eigen values and Eigen vectors of
$$\begin{bmatrix}0&0&-2\\1&2&1\\1&0&3 \end{bmatrix}$$
After getting the eigen values check relations between sum of eigen values, product of eigen values, determinant of matrix, trace of matrix

In [ ]:
from sympy import *
M = Matrix([[0,0,-2],[1,2,1],[1,0,3]])
M.eigenvals()

{1: 1, 2: 2}

In [ ]:
M.eigenvects()

[(1, 1, [Matrix([
   [-2],
   [ 1],
   [ 1]])]), (2, 2, [Matrix([
   [0],
   [1],
   [0]]), Matrix([
   [-1],
   [ 0],
   [ 1]])])]

In [ ]:
from sympy import *
M = Matrix([[1,0,0],[1,2,0],[-3,5,2]])
M.eigenvals()

{1: 1, 2: 2}

In [ ]:
M.eigenvects()

[(1, 1, [Matrix([
   [ 1/8],
   [-1/8],
   [   1]])]), (2, 2, [Matrix([
   [0],
   [0],
   [1]])])]

##Diagonalization

**Diagonalization Problem**

Given an $n \times n$ matrix $A$, does there exist an invertible matrix $P$ such that $P^{-1}AP$ is diagonal?

or

Given an $n \times n$ matrix, does $A$ have $n$ linearly independent eigenvectors?

**Procedure**


1.   Confirm that the matrix is actually diagonalizable by finding $n$ linearly independent eigenvectors. One way to do this is by finding a basis for each eigenspace and merging these basis vectors in to a single set $S$. If this set has fewer than $n$ vectors, then the matrix is not diagonalizable
2.   Form the matrix $P=\begin{bmatrix}p_1&p_2& ...& p_n\end{bmatrix}$ that has the vectors in $S$ as its column vectors
3.   The matrix $P^{-1}AP$ will be diagonal and have the eigen values $\lambda _1,\lambda _2,..,\lambda _n$ corresponding to the eigenvectors $p_1,p_2,...p_n$ as its successive diagonal entries

**Note**


1.   If $v_1,v_2,...v_k$ are eigenvectors of a matrix $A$ corresponding to distinct eigen values, then $\{v_1,v_2,...v_k\}$ is a linearly independent set
2.   If a $n \times n$ matrix $A$ has $n$ distinct eigenvalues, then $A$ is diagonalizable



Diagonal matrices are relatively easy to compute with, and similar matrices share many properties, so diagonalizable matrices are well-suited for computation. In particular, many applications involve computing large powers of a matrix, which is easy if the matrix is diagonal. But if $A = PDP^{-1}$,then $A^n = PD^nP^{-1}$

In [ ]:
from sympy import *
M = Matrix([[0,0,-2],[1,2,1],[1,0,3]])
P,D=M.diagonalize()

In [ ]:
P

Matrix([
[-2, 0, -1],
[ 1, 1,  0],
[ 1, 0,  1]])

In [ ]:
D

Matrix([
[1, 0, 0],
[0, 2, 0],
[0, 0, 2]])

In [ ]:
P**-1

Matrix([
[-1, 0, -1],
[ 1, 1,  1],
[ 1, 0,  2]])

In [ ]:
P * D * P**-1

Matrix([
[0, 0, -2],
[1, 2,  1],
[1, 0,  3]])

In [ ]:
M**13

Matrix([
[-8190,    0, -16382],
[ 8191, 8192,   8191],
[ 8191,    0,  16383]])

In [ ]:
P*D**13*P**-1

Matrix([
[-8190,    0, -16382],
[ 8191, 8192,   8191],
[ 8191,    0,  16383]])

In [ ]:
from sympy import *
M = Matrix([[1,0,0],[1,2,0],[-3,5,2]]) #Matrix is not diagonalizable
M.eigenvects()

[(1, 1, [Matrix([
   [ 1/8],
   [-1/8],
   [   1]])]), (2, 2, [Matrix([
   [0],
   [0],
   [1]])])]

#Singular Value Decomposition

Find Singular value decomposition of following matrix $A$
$$\begin{bmatrix}4&0\\3&-5\end{bmatrix}$$
Objective is to decompose $A$ as $U\Sigma V^T$ 

## Find $A^T$

In [ ]:
from sympy import *
A = Matrix([[4 ,0],[3, -5]])
ATrans=A.transpose()
ATrans

Matrix([
[4,  3],
[0, -5]])

## Find $A^TA$ (Let it be $C$)

In [ ]:
C=ATrans*A
C

Matrix([
[ 25, -15],
[-15,  25]])

## Find eigen values of $C$

In [ ]:
C.eigenvals()

{10: 1, 40: 1}

## Compute $\Sigma$ (Let it be $S$)

In [ ]:
import numpy as np
S=Matrix([[np.sqrt(40) ,0],[0, np.sqrt(10)]])
S

Matrix([
[6.32455532033676,                0],
[               0, 3.16227766016838]])

## Find eigen vectors of $A^TA$ and normalize it

In [ ]:
x=C.eigenvects()
x

[(10, 1, [Matrix([
   [1],
   [1]])]), (40, 1, [Matrix([
   [-1],
   [ 1]])])]

In [ ]:
#Normalizing eigen vector correponding to eigen value 40
import numpy as np
x1 = np.array([[-1],[1]])
normalized_x1 = x1/np.linalg.norm(x1)
print(normalized_x1)

[[-0.70710678]
 [ 0.70710678]]


In [ ]:
#Normalizing eigen vector correponding to eigen value 10
import numpy as np
x2 = np.array([[1],[1]])
normalized_x2 = x2/np.linalg.norm(x2)
print(normalized_x2)

[[0.70710678]
 [0.70710678]]


## Formulate $V$ and find $V^T$

In [ ]:
#V=[normalized_x1 normalized_x2]
V=Matrix([[-0.70710678,0.70710678],[0.70710678,0.70710678]])
V

Matrix([
[-0.70710678, 0.70710678],
[ 0.70710678, 0.70710678]])

In [ ]:
VTrans=V.transpose()
VTrans

Matrix([
[-0.70710678, 0.70710678],
[ 0.70710678, 0.70710678]])

## Compute $U$ as $AV\Sigma ^{-1}$ (Note S is variable used for $\Sigma$)

In [ ]:
U=A*V*S**-1
U

Matrix([
[-0.447213594749519,  0.894427189499039],
[-0.894427189499039, -0.447213594749519]])

## Verify $A=U\Sigma V^T$ (Note S is variable used for $\Sigma$)

In [ ]:
A

Matrix([
[4,  0],
[3, -5]])

In [ ]:
U*S*VTrans

Matrix([
[3.99999998657575,                 0],
[2.99999998993181, -4.99999998321969]])

## Using svd function

In [ ]:
import numpy as np
A = np.array([[4,0],[3,-5]])
U, S, VT = np.linalg.svd(A)

In [ ]:
U

array([[-0.4472136 , -0.89442719],
       [-0.89442719,  0.4472136 ]])

In [ ]:
S

array([6.32455532, 3.16227766])

In [ ]:
VT



array([[-0.70710678,  0.70710678],
       [-0.70710678, -0.70710678]])

**Note that eigenvectors are not unique. Multiplying by any constant, including -1 (which simply changes the sign), gives another valid eigenvector**

#Solving First Order Linear Systems

A **differential equation** is an equation involving unknown function and their derivatives. The **order** of a differential equation is the order of the highest derivative it contains.

The simplest differential equation are the **first-order** equations of the form $y'=ay$, where $y=f(x)$ is an unknown differentiable function, $y'=\frac{dy}{dx}$ is its derivative and $a$ is a constant. This equations has infinitely many solutions and they are of the form $y=ce^{ax}$, otherwise known as **general** solution.

A condition which specifies the value of the general solution at a point is called an **initial** condition, and the problem of solving a differential equation subject to an initial condition is called an **initial-value problem**

$y(0)=6$ is an example of initial condition, which means $y=6$ when $x=0$

Collection of first order differential equations is also known as **First-order linear systems**

## Case: Each equation involved has only one of the unknown functions 

Find the solution of the following first order linear system
$$y_1^{'}=3y_1$$
$$y_2^{'}=-2y_2$$
$$y_3^{'}=5y_3$$
that satisfies the initial conditions $y_1(0)=1,y_2(0)=4$ and $y_3(0)=-2$

**Step-1 : Write system in matrix form**

$$\begin{bmatrix}y_1^{'}\\y_2^{'}\\y_3^{'} \end{bmatrix}=\begin{bmatrix}3&0&0\\0&-2&0\\0&0&5 \end{bmatrix}\begin{bmatrix}y_1\\y_2\\y_3 \end{bmatrix}$$
**Step-2 : Find general solution**
$$y=\begin{bmatrix}y_1\\y_2\\y_3 \end{bmatrix}=\begin{bmatrix}c_1e^{-3x}\\c_2e^{-2x}\\c_3e^{5x} \end{bmatrix}$$
**Step-3 : Find solution satisfying initial conditions**

From given initial conditions, we obtain $c_1=1,c_2=4$ and $c_3=-2$

Solutions satisfying this conditions are $y_1=e^{3x},y_2=4e^{-2x},y_3=-2e^{5x}$


# Assignment-5

## Question-1

Find inverse of following matrix $A$
$$\begin{bmatrix}
1 & 2 & 3\\
1 & 1 & 4\\
2 & 1 & 5
\end{bmatrix}$$

(Note: Detailed steps required)

## Question-2


Using Cramer's rule find solutions for following linear system (Change values)
$$x_1+2x_2+3x_3=2$$
$$x_1+x_2+4x_3=2$$
$$2x_1+x_2+5x_3=2$$

(Note: Detailed steps required)

## Question-3

Find eigenvalues and eigenvectors of following matrix $A$
$$\begin{bmatrix}
3 & 0 & 0\\
-2 & 7 & 0\\
4 & 8 & 1
\end{bmatrix}$$

(Note: Detailed steps required)

## Question-4

Find SVD of following matrix $A$
$$\begin{bmatrix}1&1\\0&1\\1&0 \end{bmatrix}$$
(Note: Detailed steps required)

## Question-5

Find the solution of the following first order linear system
$$y_1^{'}=4y_1$$
$$y_2^{'}=-3y_2$$
$$y_3^{'}=11y_3$$
that satisfies the initial conditions $y_1(0)=-2,y_2(0)=-14$ and $y_3(0)=-21$

(Note: Detailed steps required)